apiVersion: v1
kind: Namespace
metadata:
  name: web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: web
  labels:
    app: nodejs
spec:
  replicas: 2  # Deploys 2 Node.js pods
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: node:latest  # Using the latest Node.js official image
          ports:
            - containerPort: 3000  # Default Node.js app port
          command: ["node"]
          args: ["-e", "require('http').createServer((req, res) => res.end('Hello from Node.js!')).listen(3000)"]

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: web
spec:
  selector:
    app: nodejs
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000